export const GET_ALL_MESSEGES = "GET_ALL_MESSEGES";
export const SEND_MESSEGE = "SEND_MESSEGE";
export const DElETE_MESSEGE = "DElETE_MESSEGE";
export const GET_CONVERSTAION_LIST = "GET_CONVERSTAION_LIST";
